apiVersion: v1
kind: Service
metadata:
  annotations:
    # Generate the tls for mongo 
    service.alpha.openshift.io/serving-cert-secret-name: mongodb-tls
    description: Exposes the database server
  name: mongodb
spec:
  ports:
  - name: mongodb
    port: 27017
    targetPort: 27017
  selector:
    name: mongodb
