apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
data:
  mongod.conf: |-
        ##
        ## For list of options visit:
        ## https://docs.mongodb.org/manual/reference/configuration-options/
        ##
        # systemLog Options - How to do logging
        systemLog:
          # Runs the mongod in a quiet mode that attempts to limit the amount of output
          quiet: true
        # net Options - Network interfaces settings
        net:
          # Specify port number (27017 by default)
          port: 27017
          ssl:
            mode: allowSSL
            PEMKeyFile: /etc/mongodb/pem/mongodb.pem
            CAFile: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
            allowConnectionsWithoutCertificates: true
        # storage Options - How and Where to store data
        storage:
          # Directory for datafiles (defaults to /data/db/)
          dbPath: /var/lib/mongodb/data
        # replication Options - Configures replication
        replication:
          # Specifies a maximum size in megabytes for the replication operation log (i.e. the oplog,
          # 5% of disk space by default)
          oplogSizeMB: 64
        storage.wiredTiger.engineConfig.configString: cache_size=256M
  30-set-config-file.sh: |-
        # If user provides own config file use it and do not generate new one
        if [ ! -s $MONGODB_CONFIG_PATH ]; then
           # If no configuration is provided use template
           cp ${CONTAINER_SCRIPTS_PATH}/mongod.conf.template $MONGODB_CONFIG_PATH
        fi
        [ -r "${APP_DATA}/mongodb-cfg/mongod.conf" ] && cp "${APP_DATA}/mongodb-cfg/mongod.conf" $MONGODB_CONFIG_PATH
        # decide to comment this line because
        # conf is provided as a config map and
        # we cant's rewrite /etc/mongod.conf
        # because configmap are readonly
        # Substitute environment variables in configuration file
        # TEMP=`mktemp`; cp ${MONGODB_CONFIG_PATH} $TEMP; envsubst > ${MONGODB_CONFIG_PATH} < $TEMP
        mongo_common_args+="-f ${MONGODB_CONFIG_PATH}"
